
StylesPath = .vale

MinAlertLevel = suggestion

# run `vale sync` to install packages
Packages = proselint, alex, Readability

Vocab = Terms

[formats]
qmd = md

[*.{qmd}]
BasedOnStyles = Vale, proselint, alex #, Readability
BlockIgnores = (@[\-_a-zA-Z0-9]+)|(`.+`)|([^ ]+\.[^ ]+)|([^ ]+_[^ ]+)
proselint.Typography = No
proselint.Annotations = No
alex.ProfanityUnlikely = No
