#!/usr/bin/env lua

local path = require("path")
local fs = require("path.fs")
local lustache = require("lustache")

local tmappath, inpath, outpath = arg[1], arg[2], arg[3]

if not tmappath or not inpath or not outpath then
  error("Expected three file paths as arguments.")
end
if not path.isfile(tmappath) then
  error("Mapping path '" .. tmappath .. "' is not a file.")
end
if not path.isfile(inpath) then
  error("Input path '" .. inpath .. "' is not a file.")
end
-- if path.exists(outpath) then
--   error("Output path '" .. outpath .. "' already exists.")
-- end

local mappath = path.abs(fs.tmpdir(), "mapping.ttl")

local tmapfile = assert(
  io.open(path.abs(tmappath), "r"),
  "Could not read mapping template."
)
local mapfile = assert(
  io.open(mappath, "w"),
  "Could not create temporary mapping file."
)

mapfile:write(lustache:render(tmapfile:read("*all"), {
  input = path.abs(inpath)
}))

tmapfile:close()
mapfile:close()

os.execute(table.concat({"mise rml:vw --", mappath, mappath .. ".nv"}, " "))
os.execute(table.concat({"mise rml:mp --", mappath .. ".nv", path.abs(outpath)}, " "))
-- os.execute(table.concat({"mise rml:fz --", mappath, path.abs(outpath)}, " "))
