#!/usr/bin/env bash

# [MISE] description = "Runs RMLViewer"
# [MISE] sources = [ "mappings/**/*", "!mappings/output/**/*", "!mappings/**/*_without_views.ttl", "!mappings/**/*.json" ]
# [MISE] depends = []

#--[USAGE] flag "-c --clean" help="Clean the build directory before building"
#--[USAGE] flag "-p --profile <profile>" help="Build with the specified profile" default="debug" {
#--[USAGE]   choices "debug" "release"
#--[USAGE] }
#--[USAGE] flag "-u --user <user>" help="The user to build for"
#--[USAGE] complete "user" run="mycli users"
#--[USAGE] arg "<target>" help="The target to build"

python -B $RMLVIEWER "$@"
