
duplicates=true
convert-mapping=false

strict=true
base-iri=urn:example:

serialization=nquads
outputfile=mappings/output/rmlmapper.nq

mappingfile=mappings/oauth_core/mapping_without_views.ttl
#triplesmaps=
