#!/usr/bin/env lua

local path = require("path")
local fs = require("path.fs")
local lustache = require("lustache")

local mappath, outpath = arg[1], arg[2]

if not mappath or not outpath then
  error("Expected two file paths as arguments.")
end
if not path.isfile(mappath) then
  error("Input path '" .. mappath .. "' is not a file.")
end
-- if path.exists(outpath) then
--   error("Output path '" .. outpath .. "' already exists.")
-- end

local tcfgpath = path.abs("mappings/config/rdfizer.ini")
local cfgpath = path.abs(fs.tmpdir(), "config.ini")

local tcfgfile = assert(
  io.open(tcfgpath, "r"),
  "Could not read config template."
)
local cfgfile = assert(
  io.open(cfgpath, "w"),
  "Could not create temporary config file."
)

cfgfile:write(lustache:render(tcfgfile:read("*all"), {
  mapping = path.abs(mappath),
  output_dir = path.parent(path.abs(outpath)),
  output_name = path.name(outpath)
}))

tcfgfile:close()
cfgfile:close()

fs.chdir(path.parent(mappath))

os.execute(table.concat({"$RDFIZER_CMD -c", cfgpath}, " "))
