#!/usr/bin/env lua

local path = require("path")
local fs = require("path.fs")

local mappath, outpath = arg[1], arg[2]

if not mappath or not outpath then
  error("Expected two file paths as arguments.")
end
if not path.isfile(mappath) then
  error("Input path '" .. mappath .. "' is not a file.")
end
-- if path.exists(outpath) then
--   error("Output path '" .. outpath .. "' already exists.")
-- end

fs.chdir(path.parent(mappath))

os.execute(table.concat({"$RMLVIEWER_CMD --mapping", mappath, "--output_dir", path.parent(outpath)}, " "))

fs.rename(
  path.abs(path.parent(outpath), "mapping_without_views.ttl"),
  path.abs(outpath)
)

for view in fs.glob("view*.json", 1) do
  fs.rename(view, path.abs(path.parent(outpath), view))
end
