---
title: Generalized Policy Management profile for the Grant Negotiation and Authorization Protocol
---

## Introduction

*This section is not normative.*

This document provides a mapping profile for Generalized Policy Management (GPM), targeting the IETF's *Grant Negotiation and Authorization Protocol* (GNAP). In particular, it maps parameters of the following specifications on the GPM model.

  - RFC 9635 (*Grant Negotiation and Authorization Protocol*)
  - RFC 9767 (*GNAP Resource Server Connections*)


## Mapping GNAP to GPM

The GNAP framework defines request parameters for several sequences for requesting and negotiation authorization. This document specifies GPM mappings for the GNAP **authorization request** at the *grant endpoint* of the AS. These requests are JSON objects consisting of five different aspects:

  - `client`, always required ([@map-client]);
  - `subject`, required when requesting subject information ([@map-subject]);
  - `access_token`, required when requesting an access token ([@map-token]);
  - `interact`, required if interaction is supported ([@map-interact]); and
  - `user`, optional ([@map-user]);

The following subsections map each of these aspects, resulting in one or more Policies, which MUST only contain `authorization` Rules.


### Access token {#map-token}

The `access_token` property of a GNAP authorization request is a JSON object or an array of objects, which describe authorization requirements for which a resulting token is expected. Each such object MUST be mapped to a single Policy that contains the Rules generated by its parameters.

GNAP defines the following parameters that can occur in an access token object.


#### `access`

The `access` property is *required* to obtain an access token. Its value is either a JSON object conforming to the structure of the `authorization_details` property of RFC9396 (*OAuth 2.0 Rich Authorization Requests*); or a JSON array, consisting of such objects, or strings, or both.

**Mappings**:

These objects MUST be processed in accordance with the GPM profile for OAuth 2.x. In the case of strings, the elements need to be interpreted as authorization details objects with the string's value as type, and no other explicit fields, which must be processed in the same way.


#### `label`

The `label` property is required as soon as multiple tokens are requested. Its value is a client-defined *unique string* handle for the corresponding resulting access token.

**Mappings**:

The *identifier* of each Policy MUST be set to the value of the `label` property of the corresponding `access_token` object -- prefixed with the client identifier if the value is not a valid IRI. If the request consists of a single Policy, and no `label` is given, an identifier SHOULD be minted.


#### `flags`

The `flags` property is optional. Its value is an array of strings, which represent attributes or behavior required of the corresponding access token.

**Mappings**:

For each string in the `flags` array of an `access_token` object, a *type* MUST be added to the corresponding Policy, prefixed with `urn:example:gpm:fallback:` if the string is not a valid IRI.

<!--

### Subject {#map-subject}

The `subject` property is *required* to directly obtain identity information about the end-user of the interaction. Its value is a JSON object that describes which information is requested, and can include the following fields.


#### `sub_id_formats`

The `sub_id_formats` property is *required* to obtain *identifiers* of the end-user. Its value is an array of strings, representing the expected \[RFC 9493] *Subject Identifier format(s)*.

**Mappings**:


#### `assertion_formats`

The `assertion_formats` property is *required* to obtain *assertions* about the end-user. Its value is an array of strings, representing the expected *assertion format(s)*; e.g., `id_token`, `saml2`.

**Mappings**:


#### `sub_ids`

The `sub_ids` property is *optional*. Its value is an array of JSON objects, representing known \[RFC 9493] Subject Identifiers of the (single) end-user about which additional information is being requested.

**Mappings**:

-->

### Client

The `client` property is *required*. Its value is either a string or a JSON object, which describes the client application (instance) that is making the authorization request. As an object, it can include the following fields.


#### `key`

The `key` field is *required*. Its value is either a *key object*, or a string referencing one, which represents the public key that the client will use during this interaction.

**Mappings**:


#### `class_id`

The `class_id` field is *optional*. Its value is a string, representing the software of which this client is an instance.

**Mappings**:


#### `display`

The `display` field is *optional*. Its value is a JSON object, containing additional information, which the AS can display as human-readable representation(s) of the client during this interaction.

**Mappings**:


    `name`
    : RECOMMENDED. Display name \[string] of the client software.

    `uri`
    : OPTIONAL. \[An absolute URI to] user-facing information about the client software, such as a web page.

    `logo_uri`
    : OPTIONAL. \[An absolute URI to a] a display image to represent the client software. The logo may be passed by value by using a `data:` URI referencing an image media type.


### User

The `user` property is *optional*. Its value is either a string or a JSON object, which identifies the end-user of this interaction in a verifiable way. As an object, it can include the following fields.


#### `sub_ids`

The `sub_ids` field is *optional*. Its value is an array of JSON objects, representing the \[RFC 9493] *Subject Identifier(s)* of the end user.

**Mappings**:


#### `assertions`

The `assertions` field is *optional*. Its value is an array of JSON objects, representing (verifiable) *assertions* about the end-user.

    `format`
    : REQUIRED. The assertion format \[string; e.g. `id_token`, `saml2`].

    `value`
    : REQUIRED. The assertion value as the JSON string serialization of the assertion.

**Mappings**:


<!-- #### `updated_at` (! ONLY IN RESPONSE !)

The `updated_at` field is *recommended*. Its value is a string, representing an \[RFC 3339] timestamp, which indicates when the identified account was last updated. -->


### Interact

The `interact` property is *required* if interaction is supported. Its value is a JSON object, which describes the interaction modes supported by the client application. It can include the following fields.


#### `start`

The `start` property is *required*. Its value is a JSON array of strings, objects, or both, which indicate the modes and parameters supported by the client application to *start* the interaction. It includes the following field, which in turn determines which additional parameters are needed (if any).

**Mappings**:


  ##### `mode`

  The `mode` property is *required*. Its value is a string, representing one of the modes supported by the client application to start an interaction.

  The GNAP specification defines the following start modes: `redirect`, `app`, `user_code`, `user_code_uri`.

  **Mappings**:


#### `finish`

The `finish` property is *optional*. Its value is a JSON object, indicating the mode and parameters supported by the client application to receive an indication that interaction has *finished*. It includes the following fields.

**Mappings**:


  ##### `method`

  The `method` property is *required*. Its value is a string, indicating the *callback method* the client application supports.

  The GNAP specification defines the following methods: `redirect`, `push`.

  **Mappings**:


  ##### `uri`

  The `uri` property is *required* if the `method` is `redirect` or `push`. Its value is a string that is an absolute URI without a fragment component, which the AS will use to signal the client instance that interaction has finished.

  **Mappings**:


  ##### `nonce`

  The `nonce` property is *required*. Its value is a string of ASCII characters that is unique and unguessable within the context of the AS, which will be used to calculate the `hash` parameter used in the callback.

  **Mappings**:


  ##### `hash_method`

  The `hash_method` property is *optional*. Its value is a string, representing the hash mechanism expected to calculate the callback hash.

  The GNAP specification defines the default value to be `sha-256`.

  **Mappings**:



#### `hints`

The `hints` property is *optional*. Its value is a JSON object, providing additional information concerning the interaction process. It can include the following field.

**Mappings**:


  ##### `ui_locales`

  The `ui_locales` property is *optional*. Its value is an array of strings, indicating the end-user's preferred locales for the interaction.

  **Mappings**:



## Mapping GPM to GNAP
