
[settings]
experimental = true
minimum_release_age = "0s"
github.oauth_client_id = "Iv23liLU5VXPnQQ9ONos" # apps/dev-gpm
use_versions_host = true
lockfile = true # use lockfiles = run `touch mise.lock && mise install`

[settings.aqua]
baked_registry = true # use baked-in aqua registry
slsa = true # use SLSA to verify aqua tool signatures
minisign = true # use minisign to verify aqua tool signatures
cosign = true # use cosign to verify aqua tool signatures

[settings.status]
show_env = true   # show env vars when entering a mise directory
show_tools = true # show configured tools when entering a mise directory

[env]
RMLWEAVER = { value = "{{ tools.rmlweaver.path }}/target/MappingWeaver-0.3.0.jar", tools = true }
RMLMAPPER = { value = "{{ tools.rmlmapper.path }}/rmlmapper.jar", tools = true }
RMLVIEWER = { value = "{{ tools.rmlviewer.path }}/src/rmlviewer.py", tools = true }

[deps.pip]
auto = true

[deps.luarocks]
auto = true
description = "Installs Lua modules for tasks"
sources	= [ ".mise/gpmtasks-dev-1.rockspec" ]
run	= "luarocks install --no-project --deps-only .mise/gpmtasks-dev-1.rockspec"

[tool_alias]
mustache = "aqua:cbroglie/mustache"
treefmt = "aqua:numtide/treefmt"
quarto = "pipx:quarto-cli"
rdfizer = "pipx:rdfizer"
rmlweaver = "http:RMLio/MappingWeaver-java"
rmlmapper = "github:RMLio/rmlmapper-java"
rmlviewer = "http:RMLio/rmlviewer"

[tools]
quarto = "latest"
treefmt = "latest"
vale = { version = "latest", postinstall = "vale sync" }
java = "latest"
python = "latest"
uv = "latest"
rdfizer = "latest"
rmlmapper = { version = "latest", rename_exe = "rmlmapper.jar" }
"vfox:lua" = "latest"
"aqua:cbroglie/mustache" = "latest"

"slsa-verifier" = "latest"
"cosign" = "latest"
"age" = "latest"
"sops" = "latest"
"usage" = "latest"
tinytex = "latest"
pandoc = "latest"
pipx = "latest"
maven = "latest"

[tools.rmlweaver]
version = "2b3ff94"
url = "https://api.github.com/repos/RMLio/MappingWeaver-java/tarball/{{ version }}"
format = "tar.gz"
strip_components = 1
postinstall = "mise x -C $MISE_TOOL_INSTALL_PATH java -- mvn -DskipTests package"
bin_path = "target/"

[tools.rmlviewer]
version = "01695d9" # "v2.0.0-patch1"
url = "https://api.github.com/repos/termontwouter/rmlviewer/tarball/{{ version }}"
format = "tar.gz"
strip_components = 1
postinstall = "mise x -C $MISE_TOOL_INSTALL_PATH python -- pip install -r requirements.txt"

[tasks]
setup = "mise bootstrap"
rmlweaver = "java -jar $RMLWEAVER"
rmlmapper = "java -jar $RMLMAPPER"
rmlviewer = "python -B $RMLVIEWER"
rdfizer = "rdfizer"
